name: r_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - curl
  - openssl=3.2.0
  - r-base=4.1.2
  - r-essentials
  - r-rcurl
  - r-tidyverse
  - r-cluster
  - r-compositions
  - r-clustree
  - r-uwot
  - bioconductor-scran
  - ipykernel
  - r-ggrastr
  - r-devtools
  - bioconductor-biobase
  - bioconductor-biocneighbors
  - bioconductor-biocgenerics
  - bioconductor-complexheatmap
  - snakemake
  - radian
